### ISSUE TITLE
World save erased?

### ISSUE THREAD

**Issue by JovBorkovic** [SubnauticaNitrox/Nitrox#1018]
After my friend and I were done playing for a session, I closed the server using the stop command and then exited the application. 

When I restarted the nitrox application and tried to play, i booted the server and noticed that the game said generating spawn points, and thought that didnt sound too good. 

After launching the game and joining the local server for myself I was shocked to see that the world was reset. Everything made by the players was gone and nothing remained.

I Dont have any sort of code or error message that I can offer for this issue, but i just want people to know that it exists.

**Comment by Patrik2212** [comment]
Same thing kinda happened to me and my friend, we were playing for 5 hours straight, logged out and everything was saved, logged back in to check in on the save and we had all our stuff and all cool, but the radio signals were missing, missions were stuck. So i started a new world, tried to stop the server before exiting the game to see if it's gonna work that way, but the same thing happens, equips and mats are there but there's no radio signals, no missions and it seems like the character is stuck on spawn, since there's no radio to repair since it was already done, but the server expects you to do it, therefore not giving new missions until the radio is repaired. Not sure what to do, try? Any help would be appriciated. I will upload my world for devs to try and work it out.
[https://safenote.co/r/5e8935b59ce847@30741810](url)
Thanks in advance.

**Comment by Measurity** [comment]
Quite few things story related aren't synced including signals. Save still works and isn't rerased. It just has trouble resyncing the save data with the world on rejoin. We're working on it.

**Comment by hfreist** [comment]
well we also had the issue
especially when restarting the server even if it say world saved and it worked normal
Sometimes it erases the world save and start with a new ! world 

even if we could live with the tons of sync issues ...  ths bug ruins our experience ! 

we will wait for a more advanced version of the mod ! and try again

**Comment by brianpopow** [comment]
@hfreist could you look into your nitrox log files in `Subnautica\Nitrox Logs`. Any chance you see there something along the lines `Could not load world: ...`

**Comment by hfreist** [comment]
> @hfreist could you look into your nitrox log files in `Subnautica\Nitrox Logs`. Any chance you see there something along the lines `Could not load world: ...`

[13:57:55 Server INFO]: Could not load world: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NitroxServer.GameLogic.Items.InventoryManager..ctor(List`1 inventoryItems, List`1 storageSlotItems) in C:\Users\Sunrunner\Desktop\Code\Nitrox\NitroxServer\GameLogic\Items\InventoryManager.cs:line 16
   at NitroxServer.Serialization.World.WorldPersistence.CreateWorld(DateTime serverStartTime, List`1 entities, List`1 partiallyConstructedPieces, List`1 completedBasePieceHistory, List`1 vehicles, List`1 players, List`1 inventoryItems, List`1 storageSlotItems, GameData gameData, List`1 parsedBatchCells, List`1 escapePods, String gameMode) in C:\Users\Sunrunner\Desktop\Code\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 195
   at NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() in C:\Users\Sunrunner\Desktop\Code\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 85 creating a new one.
[13:57:55 Server DEBUG]: Event Triggerer started!
[13:57:55 Server INFO]: World GameMode: Survival

**Comment by brianpopow** [comment]
@hfreist your save game was deleted because it was containing invalid data (maybe a completedbase part twice?). Sounds like a race condition issue. A possible workaround could be to check for duplicate entries and remove them in InventoryManager constructor. Maybe the reason for this issue was already fixed with #1023 (just a optimistic guess).

In any case deleting and recreating the save file on any Exception is maybe not a good idea. Maybe a backup could be made when this is done. This would have not helped in @hfreist particular case, but maybe it would at least help to find the issue.

**Comment by Jannify** [comment]
See https://github.com/SubnauticaNitrox/Nitrox/issues/1104
