### ISSUE TITLE
Server launch issue

### ISSUE THREAD

**Issue by DGrazhevsky** [SubnauticaNitrox/Nitrox#1143]
Cannot start server. When press to start - console opened and crashed. Error in logs: 

[15:17:58 Server ERROR]: System.Security.SecurityException: ECall methods must be packaged into a system module.
   at UnityEngine.DebugLogHandler.LogFormat(LogType logType, Object context, String format, Object[] args)
   at UnityEngine.Logger.Log(LogType logType, Object message)
   at LiteNetLib.NetDebug.WriteLogic(NetLogLevel logLevel, String str, Object[] args) in C:\Users\Sunrunner\Desktop\Code\Nitrox\LiteNetLib\LiteNetLib\NetDebug.cs:line 37
   at LiteNetLib.NetSocket.BindSocket(Socket socket, IPEndPoint ep, Boolean reuseAddress) in C:\Users\Sunrunner\Desktop\Code\Nitrox\LiteNetLib\LiteNetLib\NetSocket.cs:line 238
   at LiteNetLib.NetSocket.Bind(IPAddress addressIPv4, IPAddress addressIPv6, Int32 port, Boolean reuseAddress) in C:\Users\Sunrunner\Desktop\Code\Nitrox\LiteNetLib\LiteNetLib\NetSocket.cs:line 116
   at LiteNetLib.NetManager.Start(IPAddress addressIPv4, IPAddress addressIPv6, Int32 port) in C:\Users\Sunrunner\Desktop\Code\Nitrox\LiteNetLib\LiteNetLib\NetManager.cs:line 966
   at NitroxServer.Communication.NetworkingLayer.LiteNetLib.LiteNetLibServer.Start() in C:\Users\Sunrunner\Desktop\Code\Nitrox\NitroxServer\Communication\NetworkingLayer\LiteNetLib\LiteNetLibServer.cs:line 35
   at NitroxServer.Server.Start() in C:\Users\Sunrunner\Desktop\Code\Nitrox\NitroxServer\Server.cs:line 78
   at NitroxServer_Subnautica.Program.Main(String[] args)
The Zone of the assembly that failed was:
MyComputer

**Comment by Jannify** [comment]
Pls try a clean install of nitrox and check if the problem persists. If so contact our support staff on discord.
