### ISSUE TITLE
getting this error can someone help?

### ISSUE THREAD

**Issue by TomerGamerTV** [SubnauticaNitrox/Nitrox#1432]
### Version

1.4.0

### Bug

> [Press L to open log file before closing. Press any other key to close . . .
12:49:30.906] Using game files from:
[12:49:30.913] Could not load file or assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
System.IO.FileLoadException: Could not load file or assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
File name: 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
   at NitroxServer_Subnautica.Program.CurrentDomainOnAssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder)
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in C:\Users\Sunrunner\Desktop\Code\Nitrox\NitroxModel\Core\NitroxServiceLocator.cs:line 16
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)

### Expected

just crashing
### Steps to reproduce

start the server
### Other details:

[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/6096959/Player.log)

**Comment by Measurity** [comment]
Are you using a third party anti virus (Windows Defender is OK)? Add an exclusion to it for Subnautica then launch Nitrox again. If you know of any other software that might interrupt Nitrox doing its thing then disable that too.

**Comment by TomerGamerTV** [comment]
> Are you using a third party anti virus (Windows Defender is OK)? Add an exclusion to it for Subnautica then launch Nitrox again. If you know of any other software that might interrupt Nitrox doing its thing then disable that too.

hmm i just had to reinstall the game from epicgames because it didnt detect it..
now it works thx
