### ISSUE TITLE
Nitrox server & Multiplayer not loading

### ISSUE THREAD

**Issue by Aerialflame7125** [SubnauticaNitrox/Nitrox#1567]
### Version

V: 1.5.0.1

### Bug

My nitrox won't boot up. It comes with an error that says:
Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssets.ValidateMembers(ResourceAssets resourceAssets) in NitroxServer-Subnautica\Serialization\Resources\ResourceAssets.cs:line 21
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Serialization\Resources\ResourceAssetsParser.cs:line 52
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 16
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)

### Expected

It boots and instead of play it will say multiplayer, and in the cmd window it will not show red text with an error.

### Steps to reproduce

Start nitrox, Go to server, Start Server, Goto play game, Press Multiplayer, it fails.

### Install Folder
 C:\Program Files\WindowsApps\UnknownWorldsEntertainmen.GAMEPREVIEWSubnautica_1.0.7.0_x64__bh1f6rvenfkm2
yes. I have windows download. not steam.

**Comment by Measurity** [comment]
MS Store Subnautica got updated, we're waiting for Steam and Epic to also get updated to make the changes to Nitrox. Closing this issue because it's very obvious and we'll get to it ASAP.

**Comment by Aerialflame7125** [comment]
Any updates yet?

**Comment by getPoland** [comment]
lel
