### ISSUE TITLE
Server start Bug

### ISSUE THREAD

**Issue by GeneralMing** [SubnauticaNitrox/Nitrox#1664]
### Other details:

[11:42:32.242] [INF] Starting NitroxServer V1.5.0.1 for Subnautica
[11:42:32.254] [INF] Using game files from: D:\WindowsApps\UnknownWorldsEntertainmen.GAMEPREVIEWSubnautica_1.0.7.0_x64__bh1f6rvenfkm2
[11:42:32.598] [ERR] Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssets.ValidateMembers(ResourceAssets resourceAssets) in NitroxServer-Subnautica\Serialization\Resources\ResourceAssets.cs:line 21
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Serialization\Resources\ResourceAssetsParser.cs:line 52
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 16
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
[11:42:32.598] [INF] Press L to open log file before closing. Press any other key to close . . .
[11:42:52.768] [INF] Starting NitroxServer V1.5.0.1 for Subnautica
[11:42:52.779] [INF] Using game files from: D:\WindowsApps\UnknownWorldsEntertainmen.GAMEPREVIEWSubnautica_1.0.7.0_x64__bh1f6rvenfkm2
[11:42:53.026] [ERR] Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssets.ValidateMembers(ResourceAssets resourceAssets) in NitroxServer-Subnautica\Serialization\Resources\ResourceAssets.cs:line 21
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Serialization\Resources\ResourceAssetsParser.cs:line 52
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 16
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
[11:42:53.027] [INF] Press L to open log file before closing. Press any other key to close . . .
[11:43:35.435] [INF] Starting NitroxServer V1.5.0.1 for Subnautica
[11:43:35.444] [INF] Using game files from: D:\WindowsApps\UnknownWorldsEntertainmen.GAMEPREVIEWSubnautica_1.0.7.0_x64__bh1f6rvenfkm2
[11:43:35.695] [ERR] Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssets.ValidateMembers(ResourceAssets resourceAssets) in NitroxServer-Subnautica\Serialization\Resources\ResourceAssets.cs:line 21
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Serialization\Resources\ResourceAssetsParser.cs:line 52
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 16
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
[11:43:35.696] [INF] Press L to open log file before closing. Press any other key to close . . .
[11:43:53.063] [INF] Opening log file at: C:\Users\General Ming\OneDrive\Desktop\Nitrox Logs\server-20211206.log..

**Comment by Measurity** [comment]
MS Store is not supported right now because it's a new version of Subnautica that didn't make it yet to steam/epic. We're waiting on UWE to update the game on all platforms before providing support.
