### ISSUE TITLE
Value does not fall within the expected range.

### ISSUE THREAD

**Issue by pog5** [SubnauticaNitrox/Nitrox#1850]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Starting the nitrox server, dosent matter if in docked or extrernal yields this error.

### Relevant log output

[23:39:27.167] Starting NitroxServer V1.6.0.0 for Subnautica
[23:39:27.382] Using game files from: C:\Users\Nightly\Documents\Subnautica v70017
[23:39:27.545] Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssets.ValidateMembers(ResourceAssets resourceAssets) in NitroxServer-Subnautica\Serialization\Resources\ResourceAssets.cs:line 21
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Serialization\Resources\ResourceAssetsParser.cs:line 53
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 18
   at NitroxServer_Subnautica.Program.<StartServer>d__4.MoveNext() in NitroxServer-Subnautica\Program.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
[23:39:27.557] Press L to open log file before closing. Press any other key to close . . .

**Comment by NinjaPedroX** [comment]
You can get support for this in the Discord server: https://discord.gg/E8B4X9s
