### ISSUE TITLE
Json serialization error - Error resolving type specified in JSON

### ISSUE THREAD

**Issue by Zaibaii** [SubnauticaNitrox/Nitrox#1891]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Hello NitroxTeam !
Thank you for this mod !!! :)

I think the Json serialization has changed, retrieving the latest version from your repository, I have '$type' errors missing in BaseData.json and WorldData.json is this normal ?

[21:14:02.534] [ERR] Json serialization error: 
Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'NitroxModel_Subnautica.DataStructures.GameLogic.Buildings.Rotation.BaseModuleBuilderMetadata, NitroxModel-Subnautica'. Path '$type', line 1, position 9268. ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'NitroxModel_Subnautica.DataStructures.GameLogic.Buildings.Rotation.BaseModuleBuilderMetadata' in assembly 'NitroxModel-Subnautica, Version=1.6.0.1, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---

[22:26:45.263] [ERR] Json serialization error: 
Newtonsoft.Json.JsonSerializationException: Could not create an instance of type NitroxModel.DataStructures.GameLogic.ItemData. Type is an interface or abstract class and cannot be instantiated. Path 'InventoryData.InventoryItems[0].ContainerId', line 6090, position 30.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty continerProper

For play with my save, i have :
For BaseData.json, I deleted the object that referred to 'NitroxModel_Subnautica.DataStructures.GameLogic.Buildings.Rotation.BaseModuleBuilderMetadata'. (It was my bioreactor).
For WorldData.json, i add this line '"$type": "NitroxModel.DataStructures.GameLogic.BasicItemData, NitroxModel",' for all objects in "InventoryItems" and "StorageSlotItems" (I recovered this line by making a new game/save).

Exemple :
"InventoryData": {
        "InventoryItems": [{
                "$type": "NitroxModel.DataStructures.GameLogic.BasicItemData, NitroxModel",
                "ContainerId": "f4aa6a1d-9576-4513-9945-9306ba17735c",
                "ItemId": "b28760df-ea38-4cdb-b7bf-624ae3aded41",
                "SerializedData": "AggBYAgAEAAYACIIVW50YWdnZWQyJGY2NWFjNDVjLWJhMWMtNDgyNy1iNmM1LWRkMjMyMDYzZDE3ZjokNjNlMjUxYTYtZmI2NS00NTRiLTg0YjAtNDQ5M2UxOWY3M2NkSAFQAAIIAxkKFVVuaXR5RW5naW5lLlRyYW5zZm9ybRABOAoPDQAAAAAVAAAAAB0AAAAAEhQNAAAAABUAAAAAHQAAAAAlAACAPxoPDRcAgD8V/P9/Px0gAIA/DgoKUGlja3VwYWJsZRABFcI+EggAEAAYACAAKAAwATgAQARIASwKKE5pdHJveENsaWVudC5Nb25vQmVoYXZpb3Vycy5OaXRyb3hFbnRpdHkQARYKFAoSCd9gh7I46ttMEbe/Ykrjre1B"
            }, {...

The "$type" is necessary/wanted ?

Thank for  your feedback.
Have a nice day.

**Comment by dartasen** [comment]
Hello @Zaibaii, we introduced some major changes to base building making old maps incompatible with latest version, just reset your world !
