### ISSUE TITLE
Exception when launching server

### ISSUE THREAD

**Issue by guilhermicas** [SubnauticaNitrox/Nitrox#1928]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

When i attempt to launch the server, the following an exception occurs.
I execute everything as admin, and ive tried to execute the server separately as admin, doesnt work.
I have the files on a folder on Program Files.

### Describe the steps you took to encounter the bug.

I tried to open the server

### Relevant log output

```
[22:22:20.954] [INF] Starting NitroxServer Alpha v1.7.0.0 for Subnautica
[22:22:20.981] [INF] Using game files from: C:\Program Files (x86)\Steam\steamapps\common\Subnautica
[22:22:21.170] [ERR] Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssets.ValidateMembers(ResourceAssets resourceAssets) in NitroxServer-Subnautica\Serialization\Resources\ResourceAssets.cs:line 21
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Serialization\Resources\ResourceAssetsParser.cs:line 54
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 21
   at NitroxServer_Subnautica.Program.<StartServer>d__4.MoveNext() in NitroxServer-Subnautica\Program.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
[22:22:21.171] [INF] Press L to open log file before closing. Press any other key to close . . .
```

**Comment by jt-walk** [comment]
I am also getting this same exception. Only difference is Epic instead of Steam

**Comment by jt-walk** [comment]
@guilhermicas Have you set your game version to "Legacy" on steam? This is the current workaround for the Subnautica 2.0 release and fixed the issue for me

**Comment by Jannify** [comment]
https://twitter.com/ModNitrox/status/1602812078733017088
