### ISSUE TITLE
Error while trying to open a new server with Epic Games' Subnautica

### ISSUE THREAD

**Issue by 278deco** [SubnauticaNitrox/Nitrox#1933]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Epic

### Describe the issue.

When launching the server instance, the command prompt appears and immediately after, the following error is thrown : 
```
[00:15:07.347] [ERR] Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
```

I'm using the latest version of Subnautica.

### Describe the steps you took to encounter the bug.

- Download the mod.
- Extract it.
- Start Nitrox server.

### Relevant log output

```
[00:15:07.347] [ERR] Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssets.ValidateMembers(ResourceAssets resourceAssets) in NitroxServer-Subnautica\Serialization\Resources\ResourceAssets.cs:line 21
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Serialization\Resources\ResourceAssetsParser.cs:line 54
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 21
   at NitroxServer_Subnautica.Program.<StartServer>d__4.MoveNext() in NitroxServer-Subnautica\Program.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
[00:15:07.350] [INF] Press L to open log file before closing. Press any other key to close . . .
```

**Comment by RivalsRebels** [comment]
Unfortunately, if you accidentally updated to Subnautica 2.0, you won't be able to use Nitrox 1.7. You'll need to wait till we Release an Update with the Fix, which we do not have any ETA's for
