### ISSUE TITLE
Nitrox Server Isn't Working

### ISSUE THREAD

**Issue by PaytonTheGoat** [SubnauticaNitrox/Nitrox#1935]
### Describe the issue

I've downloaded everything and accepted everything but when I went to start server it said

[18:51:16.512] Starting NitroxServer Alpha v1.7.0.0 for Subnautica
[18:51:16.531] Using game files from: D:\SteamLibrary\steamapps\common\Subnautica
[18:51:16.658] Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssets.ValidateMembers(ResourceAssets resourceAssets) in NitroxServer-Subnautica\Serialization\Resources\ResourceAssets.cs:line 21
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Serialization\Resources\ResourceAssetsParser.cs:line 54
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 21
   at NitroxServer_Subnautica.Program.<StartServer>d__4.MoveNext() in NitroxServer-Subnautica\Program.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
[18:51:16.659] Press L to open log file before closing. Press any other key to close . . .
 
And I went to play and loaded and the multiplayer mod isn't there

**Comment by Jannify** [comment]
https://twitter.com/ModNitrox/status/1602812078733017088
