### ISSUE TITLE
Error when starting a server

### ISSUE THREAD

**Issue by vatug2980** [SubnauticaNitrox/Nitrox#1936]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

When I try to start a server it gives me this error: 
[02:49:14.552] Starting NitroxServer Alpha v1.7.0.0 for Subnautica
[02:49:14.569] Using game files from: D:\SteamLibrary\steamapps\common\Subnautica
[02:49:14.687] Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssets.ValidateMembers(ResourceAssets resourceAssets) in NitroxServer-Subnautica\Serialization\Resources\ResourceAssets.cs:line 21
   at NitroxServer_Subnautica.Serialization.Resources.ResourceAssetsParser.Parse() in NitroxServer-Subnautica\Serialization\Resources\ResourceAssetsParser.cs:line 54
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar[] registrars) in NitroxModel\Core\NitroxServiceLocator.cs:line 21
   at NitroxServer_Subnautica.Program.<StartServer>d__4.MoveNext() in NitroxServer-Subnautica\Program.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
[02:49:14.688] Press L to open log file before closing. Press any other key to close . . .

### Describe the steps you took to encounter the bug.

I just wanted to start a server for the first time

### Relevant log output

[game-20221223.log](https://github.com/SubnauticaNitrox/Nitrox/files/10292372/game-20221223.log)
[server-20221223.log](https://github.com/SubnauticaNitrox/Nitrox/files/10292373/server-20221223.log)

**Comment by Jannify** [comment]
https://twitter.com/ModNitrox/status/1602812078733017088
