### ISSUE TITLE
Cant start server

### ISSUE THREAD

**Issue by User3646** [SubnauticaNitrox/Nitrox#2022]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

When I try to start my server from the launcher it doesnt start and instead it comes up with a red message saying

[20:30:01.083] An exception was thrown while activating NitroxServer.Server -> NitroxServer.Serialization.World.WorldPersistence -> ?:NitroxServer_Subnautica.Serialization.SubnauticaServerJsonSerializer.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating NitroxServer.Server -> NitroxServer.Serialization.World.WorldPersistence -> ?:NitroxServer_Subnautica.Serialization.SubnauticaServerJsonSerializer. ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
   at NitroxServer.Serialization.ServerJsonSerializer..ctor()
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.<>c.<RegisterDependencies>b__0_2(IComponentContext c) in NitroxServer-Subnautica\SubnauticaServerAutoFacRegistrar.cs:line 34
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at NitroxServer_Subnautica.Program.<StartServer>d__4.MoveNext() in NitroxServer-Subnautica\Program.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)

### Describe the steps you took to encounter the bug.

I just tried to start server

**Comment by Jannify** [comment]
Pls visit our discord for help on the issue, GitHub isn't the greatest platform to provide assistant with error solving.
