### ISSUE TITLE
Update ?.

### ISSUE THREAD

**Issue by Geant200** [SubnauticaNitrox/Nitrox#2149]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

![update](https://github.com/user-attachments/assets/a8f603be-d094-4720-8530-49eecb8e5712)

### Describe the steps you took to encounter the bug.

Hello. I have just installed the latest version of the game, the same for your software and when I want to launch a server I get this error in the console, I think your software needs an update ^^.

```
[00:01:28.909] Starting NitroxServer Alpha v1.7.1.0 for Subnautica
[00:01:28.930] Due to Subnautica's recent update "Living Large", Nitrox is currently not compatible. However you can still use older version of Subnautica in order to play Nitrox. You can do so by following these steps
[00:01:28.931] Unable to start server, Nitrox isn't compatible with this Subnautica version
System.Exception: Unable to start server, Nitrox isn't compatible with this Subnautica version
   at NitroxServer_Subnautica.Program.<StartServer>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>d__3.MoveNext() in NitroxServer-Subnautica\Program.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NitroxServer_Subnautica.Program.<Main>(String[] args)
[00:01:28.932] Press L to open log file before closing. Press any other key to close . . .
```

I thank you in advance.

**Comment by oliver408i** [comment]
Come to the discord and ask for help before posting a github issue. This is intentional, you need to revert to the legacy edition
