### ISSUE TITLE
Cant Start Server (pls help)

### ISSUE THREAD

**Issue by Nater0097** [SubnauticaNitrox/Nitrox#292]
So when I try to run the server exe it runs but it gives me this error message. The first time I have ever done it worked fine but after that, it kept giving me this. I have also port forward with 11000 UCP.

ERROR: 
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] D: Event Triggerer started!
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] E: System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Lidgren.Network.NetPeer.BindSocket(Boolean reBind) in C:\Users\natha\Documents\Nitrox\lidgren-network-gen3\Lidgren.Network\NetPeer.Internal.cs:line 130
   at Lidgren.Network.NetPeer.InitializeNetwork() in C:\Users\natha\Documents\Nitrox\lidgren-network-gen3\Lidgren.Network\NetPeer.Internal.cs:line 179
   at Lidgren.Network.NetPeer.Start() in C:\Users\natha\Documents\Nitrox\lidgren-network-gen3\Lidgren.Network\NetPeer.cs:line 150
   at NitroxServer.Communication.UdpServer.Start() in C:\Users\natha\Documents\Nitrox\NitroxServer\Communication\UdpServer.cs:line 35
   at NitroxServer.Server.Start() in C:\Users\natha\Documents\Nitrox\NitroxServer\Server.cs:line 34
   at NitroxServer.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in C:\Users\natha\Documents\Nitrox\NitroxServer\MainWindow.xaml.cs:line 42

**Comment by MarijnS95** [comment]
```
[Nitrox] E: System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
```
Are you sure you have only one server running at a time?

If not, this might be related to #289.

Looks to me like the (IMHO unnecessary) WPF console window wasn't even tested properly before being PR'd.

**Comment by Nater0097** [comment]
Well, thanks!
I looked at the other issue you referenced and I guess I had another sub server running in the background. Had to close it via task manager. Working fine now!

**Comment by MarijnS95** [comment]
I don't think it's a sub-server, rather the same executable that doesn't stop because the connection thread is still up. (Note to the developer that wants to fix the bug)
