### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by LostAurora** [SubnauticaNitrox/Nitrox#339]
When i try to start the server i get this.

 `[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: No previous save file found - creating a new one.
[Nitrox] D: Event Triggerer started!
[Nitrox] E: System.IO.FileNotFoundException: Make sure resources.assets is in current or parent directory and readable.
   at NitroxServer.Serialization.ResourceAssetsParser.FindPath() in C:\Users\owlse\Documents\Nitrox\NitroxServer\Serialization\ResourceAssetsParser.cs:line 95
   at NitroxServer.Serialization.ResourceAssetsParser.Parse() in C:\Users\owlse\Documents\Nitrox\NitroxServer\Serialization\ResourceAssetsParser.cs:line 18
   at NitroxServer.Serialization.World.WorldPersistence.CreateWorld(DateTime serverStartTime, EntityData entityData, BaseData baseData, VehicleData vehicleData, InventoryData inventoryData, PlayerData playerData, GameData gameData, List`1 ParsedBatchCells) in C:\Users\owlse\Documents\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 132
   at NitroxServer.Serialization.World.WorldPersistence.CreateFreshWorld() in C:\Users\owlse\Documents\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 105
   at NitroxServer.Serialization.World.WorldPersistence.Load() in C:\Users\owlse\Documents\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 100
   at NitroxServer.Server..ctor(ServerConfigReader configReader) in C:\Users\owlse\Documents\Nitrox\NitroxServer\Server.cs:line 31
   at NitroxServer.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in C:\Users\owlse\Documents\Nitrox\NitroxServer\MainWindow.xaml.cs:line 47
`

**Comment by Zigziig** [comment]
You have to copy the file resources.assets from your subnautica data folder (Subnautica\Subnautica_Data) and place it in your "\NitroxServer\bin\Debug_WPF" folder
