### ISSUE TITLE
Cant start a server(resource.assets problem)

### ISSUE THREAD

**Issue by youdecipher** [SubnauticaNitrox/Nitrox#378]
When opening nitroxserver.exe it gives this error:

[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: No previous save file found - creating a new one.
[Nitrox] D: Event Triggerer started!
[Nitrox] E: System.IO.FileNotFoundException: Make sure resources.assets is in current or parent directory and readable.
   at NitroxServer.Serialization.ResourceAssetsParser.FindPath() in C:\Users\terrygts\Documents\Nitrox\NitroxServer\Serialization\ResourceAssetsParser.cs:line 104
   at NitroxServer.Serialization.ResourceAssetsParser.Parse() in C:\Users\terrygts\Documents\Nitrox\NitroxServer\Serialization\ResourceAssetsParser.cs:line 22
   at NitroxServer.Serialization.World.WorldPersistence.CreateWorld(DateTime serverStartTime, EntityData entityData, BaseData baseData, VehicleData vehicleData, InventoryData inventoryData, PlayerData playerData, GameData gameData, List`1 ParsedBatchCells) in C:\Users\terrygts\Documents\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 132
   at NitroxServer.Serialization.World.WorldPersistence.CreateFreshWorld() in C:\Users\terrygts\Documents\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 105
   at NitroxServer.Serialization.World.WorldPersistence.Load() in C:\Users\terrygts\Documents\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 100
   at NitroxServer.Server..ctor(ServerConfigReader configReader) in C:\Users\terrygts\Documents\Nitrox\NitroxServer\Server.cs:line 31
   at NitroxServer.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in C:\Users\terrygts\Documents\Nitrox\NitroxServer\MainWindow.xaml.cs:line 47

**Comment by youdecipher** [comment]
I saw a similar error with "Make sure resources.assets is in current or parent directory and readable."
and someone commented saying to copy subnautica_data into the debug folder of nitroxserver but that doesnt work and gives the same error

**Comment by Sajgoniarz** [comment]
There is path.txt file in server directory when you should put path of your subnautica folder, so server can fetch data from it.
