### ISSUE TITLE
Server 1.0.1.0 doesn't start under Wine

### ISSUE THREAD

**Issue by Wuestengecko** [SubnauticaNitrox/Nitrox#572]
After updating / clean installing Nitrox 1.0.1.0 from NexusMods, the server will no longer start under Wine. Version 1.0.0.9 worked fine.

Arch Linux
Wine 4.0-rc4 + staging + esync + dxvk
Installed dotnet 4.0 .. 4.7.2, DirectX 9
Epic Games Launcher version
Subnautica itself is working fine. Just the `NitroxServer.exe` crashes.

```
000b:fixme:winediag:start_process Wine Staging 4.0-rc4 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0012:fixme:reg:GetEnabledXStateFeatures 
0012:fixme:wer:WerSetFlags (2) stub!
0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0017:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
0017:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 0x993780, 0x9e1b20, 0x9e1b38) stub.
0017:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x973109, 28) stub
001a:fixme:reg:GetEnabledXStateFeatures 
001a:fixme:reg:GetEnabledXStateFeatures 
001a:fixme:heap:RtlSetHeapInformation 0x240000 0 0x23e740 4 stub
001a:fixme:wer:WerSetFlags (2) stub!
001a:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
001d:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
001d:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 0x8383e0, 0x8affa0, 0x8affc0) stub.
001d:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x8863bd, 28) stub
0009:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 0x10023780, 0x10071b20, 0x10071b38) stub.
0009:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x10003109, 28) stub
0009:fixme:reg:GetEnabledXStateFeatures 
0009:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 0x821d60, 0xcc1048, 0xcc1060) stub.
0009:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x65060d, 28) stub
0009:fixme:kernelbase:QuirkIsEnabled3 (0x32f498, 0xffffffff) stub!
0009:fixme:process:GetNumaHighestNodeNumber (0x32fbcc): semi-stub
0009:fixme:thread:SetThreadStackGuarantee (0x32fbbc): stub
0009:fixme:ntdll:EtwEventRegister ({e13c0d23-ccbc-4e12-931b-d9cc2eee27e4}, 0x92b9f0, 0xcc10b8, 0xcccb50) stub.
0009:fixme:ntdll:EtwEventRegister ({763fd754-7086-4dfe-95eb-c01a46faf4ca}, 0x92b9f0, 0xcc13c8, 0xcc1540) stub.
0009:fixme:ntdll:EtwEventRegister ({a669021c-c450-4609-a035-5af59af4df18}, 0x92b9f0, 0xccb840, 0xcccb60) stub.
0009:fixme:ntdll:EtwEventRegister ({cc2bcbba-16b6-4cf3-8990-d74c2e8af500}, 0x92b9f0, 0xcc1210, 0xcc1288) stub.
0009:fixme:wer:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 0x640000) stub!
0009:fixme:reg:GetEnabledXStateFeatures 
0009:fixme:shell:URL_ParseUrl failed to parse L"NitroxModel"
0009:fixme:shell:URL_ParseUrl failed to parse L"Autofac"
0009:fixme:nls:LocaleNameToLCID unsupported flags 8000000
0009:fixme:nls:LCIDToLocaleName unsupported flags 8000000
0009:fixme:nls:get_dummy_preferred_ui_language (0x8 0x32e2f4 (nil) 0x32e2f0) returning a dummy value (current locale)
0009:fixme:nls:get_dummy_preferred_ui_language (0x8 0x32e2f4 0x148bc8 0x32e2f0) returning a dummy value (current locale)
0009:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
0009:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0x32f040, 0x217f98, 0x32f044, 0x32f038
0009:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0x32f040, 0x217f98, 0x32f044, 0x32f038
0009:fixme:time:GetCalendarInfoEx (L"de-DE", 1, (nil), 0x20000030, (nil), 0, 0x116761c): semi-stub
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 2
0009:fixme:time:GetCalendarInfoW Unknown caltype 56
0009:fixme:time:GetCalendarInfoW Unknown caltype 55
0009:fixme:time:GetCalendarInfoW Unknown caltype 49
0009:fixme:time:GetCalendarInfoW Unknown caltype 50
0009:fixme:time:GetCalendarInfoW Unknown caltype 51
0009:fixme:time:GetCalendarInfoW Unknown caltype 52
0009:fixme:time:GetCalendarInfoW Unknown caltype 53
0009:fixme:time:GetCalendarInfoW Unknown caltype 54
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unknown caltype 57
0009:fixme:time:GetCalendarInfoW Unknown caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 2
0009:fixme:time:GetCalendarInfoW Unknown caltype 56
0009:fixme:time:GetCalendarInfoW Unknown caltype 55
0009:fixme:time:GetCalendarInfoW Unknown caltype 49
0009:fixme:time:GetCalendarInfoW Unknown caltype 50
0009:fixme:time:GetCalendarInfoW Unknown caltype 51
0009:fixme:time:GetCalendarInfoW Unknown caltype 52
0009:fixme:time:GetCalendarInfoW Unknown caltype 53
0009:fixme:time:GetCalendarInfoW Unknown caltype 54
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unknown caltype 57
0009:fixme:time:GetCalendarInfoW Unknown caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 2
0009:fixme:time:GetCalendarInfoW Unknown caltype 56
0009:fixme:time:GetCalendarInfoW Unknown caltype 55
0009:fixme:time:GetCalendarInfoW Unknown caltype 49
0009:fixme:time:GetCalendarInfoW Unknown caltype 50
0009:fixme:time:GetCalendarInfoW Unknown caltype 51
0009:fixme:time:GetCalendarInfoW Unknown caltype 52
0009:fixme:time:GetCalendarInfoW Unknown caltype 53
0009:fixme:time:GetCalendarInfoW Unknown caltype 54
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unknown caltype 57
0009:fixme:time:GetCalendarInfoW Unknown caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 2
0009:fixme:time:GetCalendarInfoW Unknown caltype 56
0009:fixme:time:GetCalendarInfoW Unknown caltype 55
0009:fixme:time:GetCalendarInfoW Unknown caltype 49
0009:fixme:time:GetCalendarInfoW Unknown caltype 50
0009:fixme:time:GetCalendarInfoW Unknown caltype 51
0009:fixme:time:GetCalendarInfoW Unknown caltype 52
0009:fixme:time:GetCalendarInfoW Unknown caltype 53
0009:fixme:time:GetCalendarInfoW Unknown caltype 54
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unknown caltype 57
0009:fixme:time:GetCalendarInfoW Unknown caltype 57
[Nitrox] Log level set to ConsoleInfo, FileLog, ConsoleDebug
0009:fixme:shell:URL_ParseUrl failed to parse L"Lidgren.Network"
0009:fixme:shell:URL_ParseUrl failed to parse L"System.Core"
0009:fixme:shell:URL_ParseUrl failed to parse L"System"
0009:fixme:shell:URL_ParseUrl failed to parse L"System.Configuration"
0009:fixme:shell:URL_ParseUrl failed to parse L"System.Xml"
0009:fixme:shell:URL_ParseUrl failed to parse L"System.Numerics"
0009:fixme:shell:URL_ParseUrl failed to parse L"System.Security"
0009:fixme:shell:URL_ParseUrl failed to parse L"System"
0009:fixme:shell:URL_ParseUrl failed to parse L"Assembly-CSharp-firstpass"
0009:fixme:shell:URL_ParseUrl failed to parse L"System"
0009:fixme:shell:URL_ParseUrl failed to parse L"UnityEngine"
0009:fixme:shell:URL_ParseUrl failed to parse L"Assembly-CSharp"
0009:fixme:shell:URL_ParseUrl failed to parse L"protobuf-net"
0009:fixme:shell:URL_ParseUrl failed to parse L"Assembly-CSharp"
0009:fixme:shell:URL_ParseUrl failed to parse L"UnityEngine.UI"
0009:fixme:shell:URL_ParseUrl failed to parse L"Newtonsoft.Json"
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
0009:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 4 0x34a4b24 0x32dbd4 0x32e228 (nil)
0009:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 0x3497a60 0x32ddc4 0x32e418 (nil)
0009:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 0x3497a60 0x32ddc4 0x32e418 (nil)
0009:fixme:process:FlushProcessWriteBuffers : stub
0009:fixme:shell:URL_ParseUrl failed to parse L"Assembly-CSharp-firstpass"
0009:fixme:shell:URL_ParseUrl failed to parse L"NitroxModel"
0009:fixme:ntdll:EtwEventRegister ({8e9f5090-2d75-4d03-8a81-e5afbf85daf1}, 0x475053e, (nil), 0x1375660) stub.
0009:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x1375624, 51) stub
[Nitrox] I: No previous save file found - creating a new one.
[Nitrox] D: Event Triggerer started!
0009:fixme:shell:URL_ParseUrl failed to parse L"AssetsTools.NET"
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
0009:fixme:shell:URL_ParseUrl failed to parse L"LitJson"
0009:fixme:shell:URL_ParseUrl failed to parse L"System.Configuration"
0009:fixme:shell:URL_ParseUrl failed to parse L"System.Xml"
0009:fixme:shell:URL_ParseUrl failed to parse L"System.Data.SqlXml"
0009:fixme:bcrypt:BCryptGetFipsAlgorithmMode 0x32df9c - semi-stub
[Nitrox] I: If playing on LAN, use this IP: 192.168.178.48
0009:fixme:winediag:IcmpCreateFile Failed to use ICMP (network ping), this requires special permissions.
0009:fixme:winediag:IcmpCreateFile Falling back to system 'ping' command as a workaround.
0009:fixme:icmp:IcmpSendEcho2 unsupported for events
0009:fixme:ver:GetCurrentPackageId (0x32d528 (nil)): stub
[Nitrox] E: System.Net.NetworkInformation.PingException: An exception occurred during a Ping request. ---> System.ComponentModel.Win32Exception: Success
   at System.Net.NetworkInformation.Ping.InternalSend(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options, Boolean async)
   at System.Net.NetworkInformation.Ping.SendAsync(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options, Object userToken)
   --- End of inner exception stack trace ---
   at System.Net.NetworkInformation.Ping.SendAsync(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options, Object userToken)
   at System.Net.NetworkInformation.Ping.SendAsync(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options, Object userToken)
   at System.Net.NetworkInformation.Ping.SendAsync(String hostNameOrAddress, Int32 timeout, Object userToken)
   at NitroxServer.IpLogger.PrintIfExternal()
   at NitroxServer.IpLogger.PrintServerIps()
   at NitroxServer.Server.Start()
   at NitroxServer.Program.Main(String[] args)
0038:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
001a:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0012:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
```

(Why do you ping Google first? Just send out the HTTP request, and if that succeeds, Internet is available.)

**Comment by Sunrunner37** [comment]
Solved in https://github.com/SubnauticaNitrox/Nitrox/commit/f6815b98ea54c3dea3a4ed041087ed3a918733e7
