### ISSUE TITLE
I'm not the only one asking this. (Installation)

### ISSUE THREAD

**Issue by ElMaxi** [SubnauticaNitrox/Nitrox#75]
OK so I'm no computer savvy so I need to ask the next: "How do I install Nitrox?" me and my friends have been mashing our heads against the wall to *decrypt* how to install this mod, so I am asking for help! I can't seem to be *smart enough* to do it myself

**Comment by Staudey** [comment]
It's not a very simple process at the moment, and if you and your friends can't follow the guide in the wiki, you should probably wait for a more accessible version in the future.

**Comment by ElMaxi** [comment]
well shit, hey I have a question to ask you, have you been able to DECRYPT those instructions?

**Comment by Measuring** [comment]
I just installed it and looks to work. Didn't properly test MP yet but the "Multiplayer" button does appear on the main menu. 

Which action exactly do you have trouble with understanding and how far did you get?

**Comment by Skyterix1991** [comment]
5. Inject NitroxPatcher into Assembly-CSharp

**Comment by urlordjames** [comment]
I’m thinking of maybe making a tutorial for Youtube, when it’s done I’ll send it to you.

**Comment by Skyterix** [comment]
Just share link here when you make it

**Comment by Measuring** [comment]
@Skyterix1991 

1. Download dnSpy from releases here: https://github.com/0xd4d/dnSpy/releases
2. Save the files from the .zip somewhere on your computer (I recommend ProgramFiles because it's a program).
3. Launch dnSpy from the dnSpy.exe (there are many files but it's there somewhere)
4. Inside dnSpy, hit ctrl+O(as in Open) or File->Open.
5. Navigate to Subnautica game directory and find CsharpAssembly.dll. Should be here: Steam\steamapps\common\Subnautica\Subnautica_Data\Managed\Assembly-CSharp.dll
6. Select and tell dnSpy to open it.
7. dnSpy should add new entrys on the left most list. Find "Assembly-Csharp" and select it.
8. In dnSpy click the search icon at the top of the program and type "GameInput".
9. At the bottom of dnSpy it should show "GameInput" and other classes of the game, find "GameInput" and double click it to open it in the edit view.
10. Press ctrl+F and now search for Awake. It should navigate you to: `private void Awake()`. That is the method you need to change.
11. Put the cursor inside that method (between the `{` and `}`) and press ctrl+shift+e.
12. dnSpy should open a new window. At the bottom left of that window click the open file icon.
13. In the open file dialog select NitroxPatcher.dll. If you followed all instructions prior it should be besides the CSharp-Assembly.dll you found earlier (same directory). If not, redo those instructions (mainly, building with Visual Studio).
14. After you opened NitroxPatcher.dll it should close the open file dialog and you're back at the Awake method.
15. Add the following to the bottom of that method (on the line before the close bracket `}`): `NitroxPatcher.Main.Execute();`.
16. Hit compile on the bottom right of the window. Wait for it to finish.
17. Close dnSpy (just hit all the X buttons on all the windows in order) and tell it to save everything (say yes and ok).

Subnautica should be patched now and a "Multiplayer" button should appear. Though there's a bug in the master branch atm so you'll have to do a tiny bugfix. See #76

**Comment by Skyterix1991** [comment]
output_log.txt
```
[Nitrox] Log level set to InGameMessages, ConsoleInfo, ConsoleDebug
[Nitrox] I: Patching Subnautica...
NullReferenceException: Object reference not set to an instance of an object
  at NitroxPatcher.Patches.ArmsController_Update_Patch..cctor () [0x00000] in <filename unknown>:0 
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for NitroxPatcher.Patches.ArmsController_Update_Patch
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, Boolean nonPublic) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[System.Type,System.Object].MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable+<CreateCastIterator>c__Iterator0`1[NitroxPatcher.Patches.NitroxPatch].MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable+<CreateGroupByIterator>c__Iterator5`2[NitroxPatcher.Patches.NitroxPatch,System.String].MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.First[IGrouping`2] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.First[IGrouping`2] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0 
  at NitroxPatcher.Main.Execute () [0x00000] in <filename unknown>:0 
  at GameInput.Awake () [0x00000] in <filename unknown>:0 
```

And compile NitroxServer erorrs:

```
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] E: System.FormatException: Invalid input string format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Single.Parse(String s)
   at NitroxServer.Serialization.WorldEntityDataParser.GetWorldEntitiesByClassId() in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\Serialization\WorldEntityDataParser.cs:line 55
   at NitroxServer.GameLogic.EntitySpawner..ctor() in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\GameLogic\Spawning\EntitySpawner.cs:line 24
   at NitroxServer.Communication.Packets.PacketHandler..ctor(PlayerManager playerManager, TimeKeeper timeKeeper, SimulationOwnership simulationOwnership) in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\Communication\Packets\PacketHandler.cs:line 26
   at NitroxServer.Server..ctor() in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\Server.cs:line 17
   at NitroxServer.Program.Main(String[] args) in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\Program.cs:line 14
```

**Comment by Sunrunner37** [comment]
This mod is not even close to a state for average users.  The instructions act as a gate to keep it limited to developers.  Please wait for an official release.
