### ISSUE TITLE
server crash on startup

### ISSUE THREAD

**Issue by CharlesAntoineSamson** [SubnauticaNitrox/Nitrox#791]
I get this:
`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at NitroxServer.Serialization.ServerProtobufSerializer.RegisterAssemblyClasses(String assemblyName) in C:\Users\Sunrunner\Desktop\Code\Nitrox\NitroxServer\Serialization\ServerProtobufSerializer.cs:line 64
   at NitroxServer.Serialization.ServerProtobufSerializer..ctor(String[] assemblies) in C:\Users\Sunrunner\Desktop\Code\Nitrox\NitroxServer\Serialization\ServerProtobufSerializer.cs:line 25
   at NitroxServer_Subnautica.SubnauticaServerAutoFacRegistrar.RegisterDependencies(ContainerBuilder containerBuilder)
   at NitroxModel.Core.NitroxServiceLocator.InitializeDependencyContainer(IAutoFacRegistrar dependencyRegistrar) in C:\Users\Sunrunner\Desktop\Code\Nitrox\NitroxModel\Core\NitroxServiceLocator.cs:line 16
   at NitroxServer_Subnautica.Program.Main(String[] args)`
I'm using épic game

**Comment by Jannify** [comment]
Is this a error from Visual Studios or Subnautica/Nitrox?  When does this happen? What is before that error?

**Comment by Measurity** [comment]
Closing this issue due to inactivity and new releases might have fixed this issue.
