### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Skyterix1991** [SubnauticaNitrox/Nitrox#84]
I have errors in console and i can't connect to server.

```
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] E: System.FormatException: Invalid input string format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Single.Parse(String s)
   at NitroxServer.Serialization.WorldEntityDataParser.GetWorldEntitiesByClassId() in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\Serialization\WorldEntityDataParser.cs:line 55
   at NitroxServer.GameLogic.EntitySpawner..ctor() in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\GameLogic\Spawning\EntitySpawner.cs:line 24
   at NitroxServer.Communication.Packets.PacketHandler..ctor(PlayerManager playerManager, TimeKeeper timeKeeper, SimulationOwnership simulationOwnership) in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\Communication\Packets\PacketHandler.cs:line 26
   at NitroxServer.Server..ctor() in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\Server.cs:line 17
   at NitroxServer.Program.Main(String[] args) in C:\Users\Skyte\Desktop\Nitrox\NitroxServer\Program.cs:line 14
```

**Comment by werichff** [comment]
same problem

**Comment by oliverslott** [comment]
I think this might be related to some culture conflicts with the `float.Parse` I'm having trouble reproducing this bug myself, but could you try to change the https://github.com/SubnauticaNitrox/Nitrox/blob/fa4cc78940d0f7be63cc8e164049da00197342bc/NitroxServer/Serialization/WorldEntityDataParser.cs#L55 line with the following code: `nextEntityInfo.localScale = new UnityEngine.Vector3(float.Parse(dimensions[0], CultureInfo.InvariantCulture), float.Parse(dimensions[1], CultureInfo.InvariantCulture), float.Parse(dimensions[2], CultureInfo.InvariantCulture));`

**Comment by werichff** [comment]
nice that works 👍

**Comment by Skyterix1991** [comment]
Everything seems to work fine in server but i still can't join server, in output_log are some errors.

Server output:
```
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: Loading batch data...
[Nitrox] I: Batch data loaded!
[Nitrox] I: Spawning entities...
[Nitrox] I: Starting Nitrox Server
```

output_log.txt: https://drive.google.com/file/d/1SEVG2WeVP8xsxCu7FoV4X06mXl3cZwfl/view?usp=sharing

**Comment by MarijnS95** [comment]
You're calling the patcher too late; it needs to do some setup work before `GameInput` sets up input bindings.

**Comment by Skyterix1991** [comment]
Still not working same errors

**Comment by Skyterix1991** [comment]
Game start something like broken world without animals even if server is off.

**Comment by MarijnS95** [comment]
> broken world without animals

See https://github.com/SubnauticaNitrox/Nitrox/pull/88
