### ISSUE TITLE
An instance of Subnautica is already running

### ISSUE THREAD

**Issue by ryanguits** [SubnauticaNitrox/Nitrox#844]
Whenever I start the Nirtox mod, it says "An instance of Subnautica is already running". I've reinstalled it two times and I still cant start Subnautica, I need help with this.

**Comment by Coding-Hen** [comment]
This might be due to the server already running. Check in task manager that
nitrox server and subnautica is not running.

**Comment by ryanguits** [comment]
It doesn't seem to work. It just keeps say it's already running. I cant think of a reason of why this is happening.

**Comment by ryanguits** [comment]
If its any help, heres a log that I cannot understand.
[20:24:11 ERROR]: System.IO.IOException: Could not open file C:\Users\ \OneDrive\Desktop\Subnautica_Data\Managed\Assembly-CSharp.dll for reading. Error: 00000003
   at dnlib.IO.MemoryMappedDataReaderFactory.Windows.Mmap(MemoryMappedDataReaderFactory creator, Boolean mapAsImage)
   at dnlib.IO.MemoryMappedDataReaderFactory.CreateWindows(String filename, Boolean mapAsImage)
   at dnlib.IO.DataReaderFactoryFactory.CreateDataReaderFactory(String fileName, Boolean mapAsImage)
   at dnlib.IO.DataReaderFactoryFactory.Create(String fileName, Boolean mapAsImage)
   at dnlib.PE.PEImage..ctor(String filename, Boolean mapAsImage, Boolean verify)
   at dnlib.DotNet.MD.MetadataFactory.Load(String fileName)
   at NitroxLauncher.Patching.NitroxEntryPatch.Remove()
   at NitroxLauncher.LauncherLogic.OnSubnauticaExited(Object sender, EventArgs e)
   at NitroxLauncher.MainWindow.CloseInternalServerAndRemovePatch()
   at NitroxLauncher.App.Application_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at NitroxLauncher.App.Main()

**Comment by Ghaarg** [comment]
Looks like you didn´t set the game directory right. You can find it on the options page in the launcher.

**Comment by ryanguits** [comment]
Thanks, I tried that but it still says its already running. Heres my install directory. C:\Program Files\Epic Games\Subnautica

**Comment by Ghaarg** [comment]
Does the error described above appear before or after you get the "Server already running"-dialoge?

**Comment by Coding-Hen** [comment]
@ryanguits is this still an issue? It might be worth also mentioning that having it inside onedrive probably isnt the best as onedrive will prevent access to the file while backing it up. I would suggest moving it to a more solid location and try again.

**Comment by Measurity** [comment]
Closed due to inactivity. If you still have issue then create a new one and reference this and/or join us on Discord.
