### ISSUE TITLE
Server unable to load save file

### ISSUE THREAD

**Issue by Her0brineCreeper** [SubnauticaNitrox/Nitrox#936]
The NitroxServer compiled from the current source code is unable to load any save files. It just fails with the following error and creates a new save:

```Could not load world: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at NitroxServer.GameLogic.Items.InventoryManager..ctor(List`1 inventoryItems, List`1 storageSlotItems) in D:\Nitrox\NitroxServer\GameLogic\Items\InventoryManager.cs:line 16
   at NitroxServer.Serialization.World.WorldPersistence.CreateWorld(DateTime serverStartTime, EntityData entityData, List`1 partiallyConstructedPieces, List`1 completedBasePieceHistory, List`1 vehicles, List`1 players, List`1 inventoryItems, List`1 storageSlotItems, GameData gameData, List`1 parsedBatchCells, List`1 escapePods, String gameMode) in D:\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 196
   at NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() in D:\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 129 creating a new one.
```

I tried it multiple times and always did the same procidure:
1. Delete the old save
2. Start the server and let it create a new one
3. Connect to the server and move around a bit
4. Disconnect, close the client and stop the server with "exit"
5. Restart it using the launcher

**Comment by Her0brineCreeper** [comment]
This issue seems to be fixed now. Well done Nitrox team.
